### ISSUE TITLE
Query "in any" doesn't seem to filter results

### ISSUE THREAD

**Issue by SoftlySplinter** [ravenscroftj/partridge#18]
I've added the queries:

Paper contains "Histogram"
Paper contains "Orientation"
Paper contains "Edges"

But it still seems to display all 260 papers in the results.

**Comment by ravenscroftj** [comment]
Thanks for finding this, I forgot to implement querying for a phrase at any location in the paper. This is a perfect argument for user testing!

Fixed in c5f15e2f908fcc88308bfec855bc4eb4dcaa37f1
